### ISSUE TITLE
Check compliance for Immutable BHoM object constructor arguments 

### ISSUE THREAD

**Issue by al-fisher** [BHoM/Test_Toolkit#103]
Provide check that Immutable BHoM object constructor arguments are identical to property names but lowercase leading letter.

i.e. 
``` C#
 public BoxProfile(double height, double width, double thickness, double outerRadius, double innerRadius, IEnumerable<ICurve> edges)
        {
            Height = height;
            Width = width;
            Thickness = thickness;
            OuterRadius = outerRadius;
            InnerRadius = innerRadius;
            Edges = new ReadOnlyCollection<ICurve>(edges.ToList());
        }
```

**Comment by awakeman** [comment]
Is it a matter of compliance that the constructor initialise *all* properties directly too? like you can't have a property that is derived from a constructor parameter and that no properties should end up uninitialised?

I assume yes but worth clarifying because it impacts how we code the check.

**Comment by al-fisher** [comment]
Yes - agreed @awakeman. Should also be included as a clear check.
Thanks

**Comment by IsakNaslundBh** [comment]
> Is it a matter of compliance that the constructor initialise all properties directly too?

Would caveat this to all immutable properties. That is at least what I have assumed when writing classes with the `IImmutable` interface.

**Comment by FraserGreenroyd** [comment]
> > Is it a matter of compliance that the constructor initialise all properties directly too?
> 
> Would caveat this to all immutable properties. That is at least what I have assumed when writing classes with the `IImmutable` interface.

If a class is implementing `IImmutable` are not all the properties then immutable by definition? Or are you referring to abstract/inheritance based properties higher up that might be coming from places that aren't implementing `IImmutable`?

**Comment by IsakNaslundBh** [comment]
> > > Is it a matter of compliance that the constructor initialise all properties directly too?
> > 
> > 
> > Would caveat this to all immutable properties. That is at least what I have assumed when writing classes with the `IImmutable` interface.
> 
> If a class is implementing `IImmutable` are not all the properties then immutable by definition? Or are you referring to abstract/inheritance based properties higher up that might be coming from places that aren't implementing `IImmutable`?

I have not takes as strict approach as that for the classes I have added that implements the interface so far. For example the section properties still have a settable material as it is safe to do so. Also, as the Material is not immutbale itself, having it as get only would only give a false sense of protection as anyone would be able to change the material internally anyway.

That + all the base properties from the BHoMObject.

**Comment by FraserGreenroyd** [comment]
> > > > Is it a matter of compliance that the constructor initialise all properties directly too?
> > > 
> > > 
> > > Would caveat this to all immutable properties. That is at least what I have assumed when writing classes with the `IImmutable` interface.
> > 
> > 
> > If a class is implementing `IImmutable` are not all the properties then immutable by definition? Or are you referring to abstract/inheritance based properties higher up that might be coming from places that aren't implementing `IImmutable`?
> 
> I have not taken as strict approach as that for the classes I have added that implements the interface so far. For example the section properties still have a settable material as it is safe to do so. Also, as the Material is not immutbale itself, having it as get only would only give a false sense of protection as anyone would be able to change the material internally anyway.
> 
> That + all the base properties from the BHoMObject.

Why would a property that might not be immutable itself (like Material) not be used in the constructor of an object that is immutable? While the property itself might be able to be set safely (as in the example above), should it not also still be set within the constructor as well, which is the purpose of this check isn't it? Or have I got confused?

**Comment by IsakNaslundBh** [comment]
> > > > > Is it a matter of compliance that the constructor initialise all properties directly too?
> > > > 
> > > > 
> > > > Would caveat this to all immutable properties. That is at least what I have assumed when writing classes with the `IImmutable` interface.
> > > 
> > > 
> > > If a class is implementing `IImmutable` are not all the properties then immutable by definition? Or are you referring to abstract/inheritance based properties higher up that might be coming from places that aren't implementing `IImmutable`?
> > 
> > 
> > I have not taken as strict approach as that for the classes I have added that implements the interface so far. For example the section properties still have a settable material as it is safe to do so. Also, as the Material is not immutbale itself, having it as get only would only give a false sense of protection as anyone would be able to change the material internally anyway.
> > That + all the base properties from the BHoMObject.
> 
> Why would a property that might not be immutable itself (like Material) not be used in the constructor of an object that is immutable? While the property itself might be able to be set safely (as in the example above), should it not also still be set within the constructor as well, which is the purpose of this check isn't it? Or have I got confused?

It for sure _could_ be. Ofc no harm in doing that, but in my mind, the question here for the compliance checks should be if it _needs_ to be. As in all get only properties needs to be set in the constructor for the object to be compliant, but any settable property could be in there or not, does not really matter.

**Comment by FraserGreenroyd** [comment]
> > > > > > Is it a matter of compliance that the constructor initialise all properties directly too?
> > > > > 
> > > > > 
> > > > > Would caveat this to all immutable properties. That is at least what I have assumed when writing classes with the `IImmutable` interface.
> > > > 
> > > > 
> > > > If a class is implementing `IImmutable` are not all the properties then immutable by definition? Or are you referring to abstract/inheritance based properties higher up that might be coming from places that aren't implementing `IImmutable`?
> > > 
> > > 
> > > I have not taken as strict approach as that for the classes I have added that implements the interface so far. For example the section properties still have a settable material as it is safe to do so. Also, as the Material is not immutbale itself, having it as get only would only give a false sense of protection as anyone would be able to change the material internally anyway.
> > > That + all the base properties from the BHoMObject.
> > 
> > 
> > Why would a property that might not be immutable itself (like Material) not be used in the constructor of an object that is immutable? While the property itself might be able to be set safely (as in the example above), should it not also still be set within the constructor as well, which is the purpose of this check isn't it? Or have I got confused?
> 
> It for sure _could_ be. Ofc no harm in doing that, but in my mind, the question here for the compliance checks should be if it _needs_ to be. As in all get only properties needs to be set in the constructor for the object to be compliant, but any settable property could be in there or not, does not really matter.

That makes sense, but if we're creating a new instance of an immutable object, it seems odd to me that there might be one or two properties which I could only set after creating the object if there wasn't an option in the constructor?

I guess this is now a question of what our compliance rule should be for this situation so we can clearly communicate it and then write the check to enforce it, but I would feel it's best to ensure every property has a matching input in the constructor, regardless of whether they also have additional set accessors?

If we opted to go instead for your suggestion @IsakNaslundBh we would need to run it as a more complex check of seeing what properties the object has, categorising them by whether they should be in the constructor or not and then checking the constructor. Not impossible by any means, but as I say, I'm just wondering if we gain anything by doing it that way vs ensuring all properties are in the constructor as above?

Just to clarify, I personally am happy either way, I just want to make sure what @awakeman and I implement is what's right for the compliance, given neither @awakeman nor I have created any immutable objects yet so you're the current expert @IsakNaslundBh :smile:

**Comment by IsakNaslundBh** [comment]
(Quoting was getting out of hand, so restarting a bit...)

> That makes sense, but if we're creating a new instance of an immutable object, it seems odd to me that there might be one or two properties which I could only set after creating the object if there wasn't an option in the constructor?

There are multiple `Create` methods across the various engines that does this, so do not see any big difference? An immutable object could still have optional properties that do not need to be set for the object to be valid, and think this distinction should be the responsibility of the object creator, not the compliance check.
Also, remember that the constructors are only accessible through the code, not the UI, so from the user side we could still have `Create` methods accepting more than only the get only parameters (Current steel and concrete `Create` methods are examples of this).
And again, I am **_not_** saying "Never add settable properties to the constructor of an immutable object". Agree with you that there will be cases were it does make sense. Just saying that IMO they do not _need_ to be there.

**Comment by FraserGreenroyd** [comment]
> (Quoting was getting out of hand, so restarting a bit...)

I knew you'd crack first :wink:

I guess my next question is on what exactly is our definition for immutable objects? I thought it was an object which couldn't change state after being created but it seems that that's not the case? It's something which has some fixed properties which shouldn't change state instead?

In which case I guess our compliance check should be, if the object implements `IImmutable`, ensure any properties which do not have a `set` accessor are matched with inputs in the constructor? Does that make sense to you @IsakNaslundBh ?

**Comment by IsakNaslundBh** [comment]
> I guess my next question is on what exactly is our definition for immutable objects? I thought it was an object which couldn't change state after being created but it seems that that's not the case? It's something which has some fixed properties which shouldn't change state instead?

Should probably go back to the reason we have them at all.
The reason they got added in the first place was to handle cases were the only clean solution for the object in question was to store non-perpendicular properties on the object itself. The sections and the profiles are not immutable because we don't want them to ever change, they are immutable because they have properties that depend on each other. For this case I see no reason why we would have to force a `SteelPlateRestraint` onto the steel section constructor when it is something you might not need to control for a particular case, and it is 100% safe to change it afterwards.
Saying this, the scope of the interface can be expanded to things like Results, which do have orthogonal properties but we want to be immutable to make sure they do not get tempered with. But for this latter case this means that they only will have get only properties, so the check would pass anyway.

> In which case I guess our compliance check should be, if the object implements IImmutable, ensure any properties which do not have a set accessor are matched with inputs in the constructor? Does that make sense to you @IsakNaslundBh ?

I think this can be split up into two checks almost:
1. Does all get only properties get assigned in the constructor
2. Does the name of the parameter in the constructor match the name of the property it is assigned to (with lowercase for parameter and uppercase for property ofc). For this latter, does not matter if it is get only or not.

This might simplify things a bit I think

**Comment by FraserGreenroyd** [comment]
That makes sense to me @IsakNaslundBh and think we can easily implement the checks that match that as we seem aligned on that :smile:

**Comment by adecler** [comment]
In case that was not mentioned in the massive conversation between @IsakNaslundBh  and @FraserGreenroyd , it is worth reminding why we need this:

In order to be able to deserialise an `IImmutable` object, we need to have a constructor that have parameters matching the properties (since that is what we have from the Bson document to reconstruct the object)

**Comment by al-fisher** [comment]
As part of implementing this check - we should review and improve wiki guidelines here also https://github.com/BHoM/documentation/wiki/The-IImmutable-interface

**Comment by FraserGreenroyd** [comment]
- [ ] HasConstructor - wiki - this checks if an object has a constructor at all, and returns an error if it does AND does not implement the `IImmutable` interface
 - [ ] HasValidConstructor - wiki - this checks if an object has a constructor and that its input match its property names

**Comment by FraserGreenroyd** [comment]
https://github.com/BHoM/documentation/wiki/HasConstructor
https://github.com/BHoM/documentation/wiki/HasOneConstructor
https://github.com/BHoM/documentation/wiki/HasValidConstructor
