### ISSUE TITLE
Rename/Creation of CodeComplianceTest_Engine

### ISSUE THREAD

**Issue by al-fisher** [BHoM/Test_Toolkit#107]
Would like to propose renaming of the current `Test_Engine` to be more specifically be called `CodeComplianceTest_Engine`.
This will allow greater scope for expanding and implementing further tests across many of the other categories of testing we are targeting. See here https://github.com/BHoM/Test_Toolkit/issues/106 although the nomenclature here is not necessarily fixed and warrants review and final decisions.

See also latest commits to Interopability PR [here ](https://github.com/BHoM/Test_Toolkit/pull/6) - creating nice separation of responsibility and focus of code.

**Comment by al-fisher** [comment]
Also to consider potential namespace as `BH.Engine.Test.CodeCompliance`

**Comment by FraserGreenroyd** [comment]
I don't see anything against that as it will allow us to further build up the test frameworks as outlined in #106 as you say. I'd be happy with the current being `CodeCompliance` as that is it's primary function :smile:

**Comment by al-fisher** [comment]
Perfect! Thanks @FraserGreenroyd
