### ISSUE TITLE
IsValidConvertMethodName does not allow for the leading I for interfaces

### ISSUE THREAD

**Issue by epignatelli** [BHoM/Test_Toolkit#157]
Asking this as a question because I can't find the conversation with the discussion (not sure there was one). 

At the moment, the `Convert` class does not allow for the leading `I` of uor `interface` methods, e.g. `IGeometry(Bar bar)`, or, morespecifically `BH.Engine.Grasshopper.Convert.IFromNode for example.
They are usually methods that only dispatch to other methods.

Is this by design, or is it a bug in the compliance check?

**Comment by FraserGreenroyd** [comment]
I don't think we considered converts could have interface methods, so if this is something we do (and we allow which would make sense to), then it is a bug in the compliance check.

FYI: @awakeman
