### ISSUE TITLE
ComplianceTest_Engine: Check compliance of Datasets

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/Test_Toolkit#187]
#### Description:

Add compliance checks of datasets to make sure that (to start with)

- Each json file contains exactly 1 object
- The object in the json should be a Dataset obejct

**Comment by IsakNaslundBh** [comment]
Was about to raise this issue again, but found that I already had.

Case where this would have been helpful here : https://github.com/BHoM/BHoM_Datasets/pull/56#issuecomment-672752481

:)

**Comment by FraserGreenroyd** [comment]
As discussed with @IsakNaslundBh the following will be implemented:

 - An error if a dataset json file does not deserialise into a `Dataset` object
 - An error if a dataset contains more than one object
 - A warning if the dataset does not contain any source information
