### ISSUE TITLE
CodeCompliance: Namespace should match folder path

### ISSUE THREAD

**Issue by FraserGreenroyd** [BHoM/Test_Toolkit#202]
Following discussion with @adecler @IsakNaslundBh @awakeman and @al-fisher 

The namespace of a file should match the folder structure within **Engine namespaces** after the discipline part of the engine.

Engine namespaces always start as `BH.Engine.Discipline` or `BH.Engine.External.Discipline` - everything after this part should then match the folder structure of the file.

For example, if an engine has a sub-folder in the create folder that looks like `Engine/Create/MySubFolder/MyFile.cs` then the namespace should be `BH.Engine.Discipline.MySubFolder`.

This is a new compliance check for the 3.2 milestone. The check and associated documentation should be created and turned on.

**Comment by IsakNaslundBh** [comment]
For `Create` methods in particular, I thought we said that the folders should match the objects sub-namespace, rather than the method sub-namespace?

For all others, agree.

**Comment by FraserGreenroyd** [comment]
Yes we did @IsakNaslundBh however that's not possible with a static check and will end up being a compiled check with human reviewers doing the manual checks in the first instance. Sorry, should have made that clearer.

In this scenario, it will be down to a human reviewer to check that create method folders match object folders from the oM because the static check doesn't have access to that information, this check will only check file namespace and path structure.

A future compiled check will be done to then check the folder structure is accurate against the objects namespace for create methods. Does that make sense?

**Comment by IsakNaslundBh** [comment]
It does. 

Question though, do the create methods in subfolders, matching oM namespace, need to sit in Engine sub-namespaces as well? In structure engine the only place we have subfolder is for create methods, matching the oM namespace, but we only have a single namespace across the full Engine. Will that need to change?

**Comment by FraserGreenroyd** [comment]
I think in the first instance @IsakNaslundBh we will produce this check and then run an audit to get a scale of how much things might have to change to then inform what we do next. So I can't say for certain if engine methods would need to update because we might opt not to keep the check after audit, but, under the wording of the issue I would say yes, if we opt to keep the check they would need to change.

**Comment by FraserGreenroyd** [comment]
Moving to 3.3. milestone as will not be accomplished before end of feature development for 3.2

**Comment by FraserGreenroyd** [comment]
Over the last 4 years this didn't get completed, we have changed our strategy around this and opted to be more flexible in general on certain rules. As such, this rule is not enforced anywhere that I have seen in the last several months/years, and there have been many debates on allowing flexibility to inject into higher namespaces from sub-folders. As such, for the time being, I am closing this issue as a will not action, as it is down to individual toolkit maintainers to decide the best approach for their repository while following the guidelines of [BHoM development](https://bhom.xyz/documentation).
