### ISSUE TITLE
Test_Toolkit: Compliance check if a deprecated method is being called by another method

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/Test_Toolkit#25]
#### Description:

A check if a method with a deprecated attribute is being called from another method. Could be across toolkits or in the same repo.

**Comment by FraserGreenroyd** [comment]
Accidentally closed, sorry for any confusion @IsakNaslundBh ! Reopened to be actually addressed at some point :smile:

**Comment by FraserGreenroyd** [comment]
@IsakNaslundBh we no longer have or use the `Deprecated` attribute now - do we still want such a check with the `ToBeRemoved` option instead?

The `PreviousVersion` I think is fine as that'll be picked up by other checks (installer, core), so it's just whether we want to do something about `ToBeRemoved` or wait till it gets removed and then use installer checks to flag it?

**Comment by IsakNaslundBh** [comment]
The introduction of `PreviousVersion` made this less critical, as we generally just remove the method straight away now, so if you have other things in the backlog, would not put this on the top of the list.

Saying that, this would be a nice to have, but understand this is a bit more complicated as it needs to look at dependencies across toolkits etc.

So in summary, yes, I think it still could be useful for the `ToBeRemoved`, but not critical.

**Comment by FraserGreenroyd** [comment]
In the last 2 years since this issue was last commented on, we've massively expanded our checking system with `installer` and `versioning`. I feel now, if someone did delete a method which was previously `ToBeRemoved` or `Deprecated`, we would pick that up at the PR level before the PR was merged, making a specific check for such an action redundant and not worth the hassle in trying to implement, so I'm closing this issue @IsakNaslundBh - but feel free to reopen if you feel strongly otherwise! 😄

**Comment by IsakNaslundBh** [comment]
Yah, can get behind this, now that the strategy is to for most cases simply version things that are being removed.

Think I raised this quite some time before we had versioning in place, and where there were cases of toolkits calling quite a few methods that was supposed to not be there (deprecated) and quite a hassle of realigning could happen when you tried to remove them later.

Agree, with versioning and check-installer, this is no longer as relevant, and also fully understand that this would be quite a complicated beast to crack, so not worth the effort. Happy for this to be closed.
