### ISSUE TITLE
IsValidQuantityInputAttribute check will always be true

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/Test_Toolkit#297]
#### Description:

The loop below checks whether the strongly typed property contains an object of that certain type, which will always be true.
https://github.com/BHoM/Test_Toolkit/blob/ed6ffad8d1949b72147a4c98b4c5f87b0ffa9683/CodeComplianceTest_Engine/Query/DynamicChecks/IsValidQuantityInputAttribute.cs#L42-L49

As discussed with @IsakNaslundBh, it may be hard to effectively test this one as the property will simply stay equal to `null` in case its constructor gets fed with wrong type.

https://github.com/BHoM/BHoM/blob/49b56b2370b198591cbf371ea7f230ca374d27f8/Reflection_oM/Attributes/InputAttribute.cs#L47-L55

**Comment by FraserGreenroyd** [comment]
Yes this is by design, this particular check is within the Dynamic section and is still in prototype phase. It had to be updated in order to compile, but currently does as its designed for now :smile:
