### ISSUE TITLE
Core BHoM namespace checks fail erroneously

### ISSUE THREAD

**Issue by awakeman** [BHoM/Test_Toolkit#30]
#### Description:

BHoM (`BH.oM.Base`), BHoM_Engine (`BH.Engine.Base`), BHoM_Adapter (`BH.Adapter`) and BHoM_UI (`BH.UI`) namespaces fail compliance check since they aren't of the form described by the Regular Expression:
```
s/([A-Za-z0-9]+)_(Engine|oM|Adapter|UI)/BH.\2.\1/
```
(e.g. Reflection_Engine => `BH.Engine.Reflection`)

#### How to replicate:

Run compliance check on files for the aforementioned projects, observe the namespace check failure.

#### Expected behaviour:

These namespaces should be treated as valid (when in the correct location)

**Comment by FraserGreenroyd** [comment]
Owing to the decision to allow namespace injection, this check will not be turned on so resolving this issue is not relevant.
