### ISSUE TITLE
Modify clone check is too sensitive

### ISSUE THREAD

**Issue by awakeman** [BHoM/Test_Toolkit#33]
#### Description:

The Modify method test for cloning the object expects the clone to happen in the first statement. However some instances have things like null checks on the object to be cloned on their first line which i'd argue should be valid.

**Comment by FraserGreenroyd** [comment]
I would agree with your argument that `null` checks should be valid prior to the clone command.

**Comment by FraserGreenroyd** [comment]
Following discussion today, this check is to be removed entirely.
