### ISSUE TITLE
Unit test error message ends in the middle of the line

### ISSUE THREAD

**Issue by LMarkowski** [BHoM/Test_Toolkit#338]
#### Description:

Not sure if it's the best place to raise that one, but wasn't sure where to raise @BHoMBot issues. It would be nice though to have the messages fully displayed.

![image](https://user-images.githubusercontent.com/48125514/114716894-cd1ca980-9d34-11eb-9881-28235a30e50a.png)

#### Steps to reproduce:

Create a method that fails tremendously. :v

#### Expected behaviour:

Should be displayed fully.

#### Test file(s):

Difficult to obtain as I'm fixing the bug rn.

**Comment by FraserGreenroyd** [comment]
This is actually a problem with GitHub truncating messages that are too large, I've noticed the same with the null check reports. This isn't something that we can fix alas (other than not having dodgy code 😉 )
