### ISSUE TITLE
Test_Toolkit not allowing Grasshopper to startup

### ISSUE THREAD

**Issue by peterjamesnugent** [BHoM/Test_Toolkit#341]
#### Description:

Upon building the Test_Toolkit from /master Grasshopper no longer opens.
![image](https://user-images.githubusercontent.com/30078587/118802111-a9033980-b899-11eb-8a4c-8787004d7745.png)

#### Steps to reproduce:

1. Build latest installer
2. Build this branch (to be tested) https://github.com/BHoM/BHoM_Engine/pull/2504
3. Run Rhino 6 + Grasshopper (successfully)
4. Build Test_Toolkit 
5. Try to run Rhino 6 + Grasshopper

I've tried to remove the plugins, clear the Library for Grasshopper etc. The only fix seems to be NOT building Test_Toolkit.

#### Expected behaviour:

Grasshopper to open.

**Comment by FraserGreenroyd** [comment]
@peterjamesnugent I am unable to replicate this issue following your steps, or following other steps. Building Test_Toolkit on top of an installer does not prevent Grasshopper from opening, and compiling the mentioned Engine PR then opening Grasshopper also works fine.

I'm closing this for now but if you have more information/evidence to help track it down then feel free to reopen! :smile:
