### ISSUE TITLE
Test_Engine: IsEqual method to ignore static properties

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/Test_Toolkit#361]
#### Description:

The IsEqual that returns differences between two objects is meant to be checking differences between two instances of objects. Therefor static properties should be safe to ignore.

Problem with including static properties becomes evident when trying to compare for example two `System.Drawing.Color` with each other, where every statically defined colour is compared, and even worse, it is done recursively, making it take many seconds to compare a simple list of a few 100 colours. Turning of static properties gets it down to a few ms, which is what one would expect.

@FraserGreenroyd @al-fisher @alelom  FYI

**Comment by FraserGreenroyd** [comment]
Just to add that @IsakNaslundBh and myself have been discussing this a bit this morning and I am in agreement with the ignoring of static properties when comparing objects.

I said to @IsakNaslundBh

> A static property is, by definition, static
> It's the same value across two instantiations of an object
> So comparing it for the purposes of our unit tests, or our push/pull compare, is redundant IMO

So am in agreement with turning that setting off moving forward.

**Comment by alelom** [comment]
I think I can agree to that. However, I'd expose a new input like `bool compareStaticMembers = false` and add sth like:

```cs
if (compareStaticMembers)
{
    comparer.Config.CompareStaticFields = false;
    comparer.Config.CompareStaticProperties = false;
}
```

Simply because:
- from the name `IsEqual()` you can't discern that static fields/props are by default skipped
- we expose other default comparison configurations through other inputs, i.e. `BH.oM.Base.ComparisonConfig config`

(Arguably we should do the same for the `MaxDifferences` config important)

**Comment by IsakNaslundBh** [comment]
> from the name IsEqual() you can't discern that static fields/props are by default skipped

Get your point, but would argue that you should be able to skip them, as static members are by definition, well, static, and therefor should be equal across all objects of the same type.

Would honestly have assumed them to not be included by default really, and the only sort of edge case difference I can think of for looking at them at all would be if static properties between objects of different types were compared (which I think kellerman allows you to check if you set up the config in some specific way). That should not be the case for the current use of the method though.

> we expose other default comparison configurations through other inputs, i.e. BH.oM.Base.ComparisonConfig config (although arguably we still miss to expose the MaxDifferences config, we should probably expose that too)

Could add it here as well, but makes for a slightly larger refactoring, and as mentioned above, I do not think it should be needed really.
