### ISSUE TITLE
Review of CreateCompliance

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/Test_Toolkit#384]
#### Description:

For some cases, the requirement on Create methods to exactly match the file name can be to stringent, leading to having to create a multitude of files, which can make the code more unreadable and harder to find. For example see https://github.com/BHoM/BHoM_Engine/pull/2802/checks?check_run_id=6504261317

While this requirement (exact match of method name to file name) can make sense for some namespaces, there are namespaces like geometry where it might make things worse.

Worth discussing how to best handle this, if it is worth loosening the check slightly (to similar requirements that is put on other engine methods, methodName must contain filename) or something else.

**Comment by FraserGreenroyd** [comment]
Following review and discussion offline on this, it's been agreed that `Create` method names should contain their file name, same as `Query`, `Compute`, and other parts of the Engines. As such, the strict matching is being removed (#456) and replaced with the contains check.
