### ISSUE TITLE
Location object to contain file name and span

### ISSUE THREAD

**Issue by FraserGreenroyd** [BHoM/Test_Toolkit#42]
Create a Location object which will contain a file name/path and the span of the error for locations where errors occur.

Update `RunChecks` to provide the file name to the Error (and create method to take in a location).

Create a convert for Location to string (@awakeman to provide the format wanted for Location string) and a convert for Error to string (@awakeman to do same for that).

**Comment by awakeman** [comment]
would suggest something like:

```
"in {filepath} at {line}:{column}"
```

for the format of Locations
