### ISSUE TITLE
Delete CodeComplianceTest_Test/RunTest.cs

### ISSUE THREAD

**Issue by desaiwangBH** [BHoM/Test_Toolkit#449]
#### Description

Fraser said that this [file](https://github.com/BHoM/Test_Toolkit/blob/528e6c377d72dd11c3eb83680634b2248c5a601f/CodeComplianceTest_Test/RunTest.cs) is outdated, and should be removed. 

interesting, does string concatenation to generate correct documentation link:
https://github.com/BHoM/Test_Toolkit/blob/528e6c377d72dd11c3eb83680634b2248c5a601f/CodeComplianceTest_Test/RunTest.cs#L78

**Comment by travispotterBH** [comment]
@desaiwangBH  work for week of 6/26 - 6/30
