### ISSUE TITLE
IsDocumentationURLValid fails for a valid URL

### ISSUE THREAD

**Issue by peterjamesnugent** [BHoM/Test_Toolkit#457]
#### Description:

The check fails for a valid URL.

#### Steps to reproduce:

https://github.com/BHoM/BHoM/pull/1545/checks?check_run_id=16305039317

#### Expected behaviour:

Valid pass 

#### Test file(s):

`        [DocumentationURL("https://bhom.xyz/documentation/Conventions/BHoM-Structural-Conventions/", DocumentationType.Documentation)]`

Currently on this PR: https://github.com/BHoM/BHoM/pull/1545

**Comment by FraserGreenroyd** [comment]
Well this is frustrating - run it from within Grasshopper and it's a pass!

![image](https://github.com/BHoM/Test_Toolkit/assets/18049174/5a2ca4c3-3190-48f8-85c1-9b5004f9a0e9)
