### ISSUE TITLE
Compliance check for methods implemented for interfaces 

### ISSUE THREAD

**Issue by al-fisher** [BHoM/Test_Toolkit#48]
One of the challenges we have with implementing our interfaces in BHoM - resulting from our separation of oM and Engine across multiple .dlls - is it is hard to know or enforce which methods are required for objects implementing interfaces.

There have been a couple of recent examples - around our `IElementXD` interfaces and `IGeometry` interface for `FramingElement` and `Basis` receptively.

Suggestion here is to add an additional compliance check - to ensure these methods are implemented.

In order to achieve the above this will of course also require us to define/document somewhere what those methods are, for each interface - as we are not currently doing that centrally

@adecler @FraserGreenroyd @rwemay

**Comment by adecler** [comment]
If I remember correctly, I had done something of the sort in the past. Not sure if it was code or script but, either way, the process was quite simple and didn't need a catalogue of methods to check:
- Collect the list of BHoM objects that implement each BHoM interface
- Collect all `I` methods from the Engine that have an interface as first argument
- Make sure that we can find methods with the same name for each class implementing the interface
