### ISSUE TITLE
Review messages for tests

### ISSUE THREAD

**Issue by awakeman** [BHoM/Test_Toolkit#55]
Below is a list of all the messages given for failing each of the tests, would be good to review wording to give a consistent style for all of them.

- *ContainsCopyright(CompilationUnitSyntax)*: Copyright message is invalid
- *DescriptionAttributePresent(MethodDeclarationSyntax)*: Engine Method must contain a Description attrubute
- *DescriptionAttributePresent(ConstructorDeclarationSyntax)*: Adapter constructor must contain a Description attrubute
- *EngineClassMatchesFilePath(ClassDeclarationSyntax)*: Incorrect Engine class based on file path
- *OutputAttributePresent(MethodDeclarationSyntax)*: Method must contain an Output or MultiOutput attribute
- *OutputAttributePresent(ConstructorDeclarationSyntax)*: Method must contain an Output or MultiOutput attribute
- *InputAttributeHasParameter(AttributeSyntax)*: Input attribute does not match any parameter
- *ParameterHasInputDescription(ParameterSyntax)*: Input requires a matching Input attribute
- *UniqueOutputAttribute(AttributeSyntax)*: Method cannot contain more than one Output attribute
- *UniqueDescriptionAttribute(AttributeSyntax)*: Method cannot contain more than one Description attribute
- *NamespaceMatchesFilePath(NamespaceDeclarationSyntax)*: Namespace is incorrect based on file path
- *NameMatchesFileName(ClassDeclarationSyntax)*: Class name must match filename
- *NameMatchesFileName(MethodDeclarationSyntax)*: Method name must match filename
- *IsValidModifyMethod(MethodDeclarationSyntax): Invalid Modify method*: Modify method does not contain a suitable cloning statement in its first line. Cloning input objects are required to ensure upstream objects are not changed inadvertantly
- *ModifyReturnsSameType(MethodDeclarationSyntax)*: Modify methods must return the same type as their first parameter
- *HasSingleNamespace(NamespaceDeclarationSyntax)*: Files cannot contain more than one namespace
- *IsPublicClass(ClassDeclarationSyntax): Invalid Engine class*: Engine classes must be public
- *PropertyAccessorsHaveNoBody(PropertyDeclarationSyntax): Invalid oM property*: Object property accessors must not have a body
- *PropertyHasPublicGet(PropertyDeclarationSyntax): Invalid oM property*: Object properties must have a public getter
- *PropertyIsPublic(PropertyDeclarationSyntax): Invalid oM property*: Object properties must be public
- *ObjectHasOnlyProperties(FieldDeclarationSyntax)*: BHoM Objects cannot contain fields, only properties
- *ObjectHasOnlyProperties(MethodDeclarationSyntax)*: BHoM Objects cannot contain methods or constructors, only properties
- *ObjectHasOnlyProperties(ConstructorDeclarationSyntax)*: BHoM Objects cannot contain methods or constructors, only properties
- *IsValidCreateMethodName(MethodDeclarationSyntax): Invalid Create method name*: Method name must have the same name as its return type
- *IsValidConvertMethodName(MethodDeclarationSyntax): Convert method name invalid*: Method name must begin with either 'To' or 'From'
- *IsStaticClass(ClassDeclarationSyntax): Invalid Engine class*: Engine classes must be static
- *IsValidEngineClassName(ClassDeclarationSyntax)*: Invalid Engine class name

**Comment by FraserGreenroyd** [comment]
Would also be good to add the attribute for URLs to definitions of these compliance checks for when the wiki documentation is updated.

**Comment by FraserGreenroyd** [comment]
Following discussion @al-fisher plans to review this today and provide comments of changes he'd like to see :smile:

**Comment by awakeman** [comment]
Great, thanks both

**Comment by al-fisher** [comment]
- ***HasValid**Copyright(CompilationUnitSyntax)*: Copyright message is invalid
- ***HasDescriptionAttribute**(MethodDeclarationSyntax)*: Engine Method must contain a Description **attribute**
- ***HasDescriptionAttribute**(ConstructorDeclarationSyntax)*: Adapter constructor must contain a Description **attribute**

> ^^ Replaced "Present" Suffix with "Has" Prefix"

- *EngineClassMatchesFilePath(ClassDeclarationSyntax)*: Incorrect Engine class **name** based on file path
- *OutputAttributePresent(MethodDeclarationSyntax)*: Method must contain an Output or MultiOutput attribute
- *OutputAttributePresent(ConstructorDeclarationSyntax)*: Method must contain an Output or MultiOutput attribute

> ^^ Same with two above - should we replace "Present" Suffix with "Has" Prefix"?


- *InputAttribute**Matches**Parameter(AttributeSyntax)*: Input attribute does not match **any of the given parameters**
- ***HasMatching**InputDescription(ParameterSyntax)*: Input **Parameter** requires a matching Input attribute
- ***Is**UniqueOutputAttribute(AttributeSyntax)*: Method cannot contain more than one Output attribute
> ^^ Prefix with "Is"?

- ***Is**UniqueDescriptionAttribute(AttributeSyntax)*: Method cannot contain more than one Description attribute
> ^^ Prefix with "Is"?

- ***NamespaceMatchesFilePath(NamespaceDeclarationSyntax)*: Namespace is incorrect based on file path**
> ^^ is the one above removed now?


- *NameMatchesFileName(ClassDeclarationSyntax)*: Class name must match **file name**
- *NameMatchesFileName(MethodDeclarationSyntax)*: Method name must match **file name**
- *IsValidModifyMethod(MethodDeclarationSyntax): Invalid Modify method*: Modify method does not contain a suitable cloning statement in its first line. Cloning input objects are required to ensure upstream objects are not changed **inadvertently** (sp)
> ^^ also is the one above removed now?

- *ModifyReturnsSameType(MethodDeclarationSyntax)*: Modify methods must return the same type as their first parameter
- *HasSingleNamespace(NamespaceDeclarationSyntax)*: Files cannot contain more than one namespace
- *IsPublicClass(ClassDeclarationSyntax): Invalid Engine class*: Engine classes must be public
- *PropertyAccessorsHaveNoBody(PropertyDeclarationSyntax): Invalid oM property*: Object property accessors must not have a body
- ***HasPublicGet**(PropertyDeclarationSyntax): Invalid oM property*: Object properties must have a public getter

> ^^ Removed the *Property* prefix to that method as matches the *HasX* method style and *Property* is implicit from the arguments @awakeman @FraserGreenroyd would you agree?

- ***IsPublicProperty**(PropertyDeclarationSyntax): Invalid oM property*: Object properties must be public
- *ObjectHasOnlyProperties(FieldDeclarationSyntax)*: BHoM Objects cannot contain fields, only properties
- *ObjectHasOnlyProperties(MethodDeclarationSyntax)*: BHoM Objects cannot contain methods or constructors, only properties
- *ObjectHasOnlyProperties(ConstructorDeclarationSyntax)*: BHoM Objects cannot contain methods or constructors, only properties

> ^^ for the three above - do we need the *Object* Prefix - question? @awakeman @FraserGreenroyd 

- *IsValidCreateMethodName(MethodDeclarationSyntax): Invalid Create method name*: Method name must have the same name as its return type
- *IsValidConvertMethodName(MethodDeclarationSyntax): Convert method name invalid*: Method name must begin with either 'To' or 'From'

> ^^ This feedback is wrong as @awakeman you mentioned - review against rules.
Is it "ToBHoM" and "FromBHoM" actually? Or was this too restrictive. Check what we are checking here again probably.

- *IsStaticClass(ClassDeclarationSyntax): Invalid Engine class*: Engine classes must be static
- *IsValidEngineClassName(ClassDeclarationSyntax)*: Invalid Engine class name


---

Ok - super. Thanks @awakeman.
Have reviewed the above. Some suggested renaming to align consistancy of terminology of method names - using "Is" and "Has" etc.
Tried to make clear my other edits by using **bold**.
Please review
FYI @FraserGreenroyd @adecler

**Comment by FraserGreenroyd** [comment]
@awakeman FYI have added to milestone for completion this week by one of us
