### ISSUE TITLE
Test_Toolkit: Add compliance checks for adapter projects

### ISSUE THREAD

**Issue by FraserGreenroyd** [BHoM/Test_Toolkit#72]
@alelom to provide a list of the 'rules' for adapters that could/should be checked by Test_Toolkit.

**Comment by alelom** [comment]
So for this "first level of compliance", as discussed with @al-fisher, the main and only item is to check the namespaces as per
https://github.com/BuroHappoldEngineering/Operations_Toolkit/issues/100

All "external" (meaning, non BHoM) software Schemas and Method must follow the following convention:

- oM:
   - BH.oM.External.Revit
   - BH.oM.External.GSA
   - BH.oM.External.Dynamo
- Engine:
   - BH.Engine.External.Revit
   - BH.Engine.External.GSA

**Comment by FraserGreenroyd** [comment]
Do they sit within Adapter folders @alelom or as separate projects?

Namespace checking of `BH.Adapter.XYZ` is already implemented I believe isn't it @awakeman ?

**Comment by awakeman** [comment]
>Namespace checking of BH.Adapter.XYZ is already implemented I believe isn't it @awakeman ?

that is correct

**Comment by FraserGreenroyd** [comment]
> > Namespace checking of BH.Adapter.XYZ is already implemented I believe isn't it @awakeman ?
> 
> that is correct

Ok great, in that case @alelom if you could confirm the above and we can get something worked up :smile: I'm pushing this back to 3.1MVP though because it's a little tight to get this in with our other commitments by the end of this sprint.

**Comment by FraserGreenroyd** [comment]
As adapter compliance grows, discrete issues will be raised similar to #141

**Comment by al-fisher** [comment]
Reading the above - and a quick check in the code - am I right in saying we have not implemented a namespace check to ensure Adapter oMs and Engines are **External** yet?

See @alelom message above https://github.com/BHoM/Test_Toolkit/issues/72#issuecomment-559190324

Raising now as this is a compliance issue that as a direct impact on UI so (along with compliance that is impactful for the API) will be good to prioritise as we implement more checks


@FraserGreenroyd @awakeman @alelom

**Comment by FraserGreenroyd** [comment]
@al-fisher yes that's correct, there is currently no explicit check for External keywords in the namespaces.

I am not sure we would be able to implement on, as we've seen in the past with problems with injecting into namespaces and filepath checks, I think we need to have a discussion on the exact discrete conditions in which the External keyword should be used in namespaces that would allow us to create the right CI check moving forward. I would be cautious against provisioning any immediate checks given our current resourcing/timelines until we bottom that out.

**Comment by al-fisher** [comment]
> I would be cautious against provisioning any immediate checks given our current resourcing/timelines until we bottom that out.

Agreed - as noted here: https://github.com/BHoM/BHoM_Adapter/issues/210 would not wait for formal implementation in Compliance checks to fix the issues in the Toolkits.

Discussion sounds good though.
As you suggest above - do you want to raise a discrete issue for this External check and we can plan from there. Assigned to 3.2 MVP. 
Cheers 😄
