### ISSUE TITLE
Compliance: Convert methods should have correct return type 

### ISSUE THREAD

**Issue by awakeman** [BHoM/Test_Toolkit#84]
#### Description:

- To methods should take a BHoM Object
- From methods should return a BHoM Object

**Comment by awakeman** [comment]
Note: this is a check that needs compiled library due to needing dependency information.

**Comment by FraserGreenroyd** [comment]
Following discussion in the workshop with @al-fisher @adecler @IsakNaslundBh and @awakeman :

 - From methods cannot have a BHoM object as its first argument
 - To methods cannot return a BHoM object
 - Convert methods which do not have a BHoM object as input or output are valid

@awakeman to update the draft PR as appropriate
